name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: |
          pip install -r ingest/requirements.txt
          pip install flake8 dbt-core dbt-duckdb
      - run: flake8 ingest spark_jobs
      - name: dbt run & test
        run: |
          cd dbt && dbt deps && dbt run -m +fact_trip_punctuality && dbt test
  terraform:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check
      - run: terraform init
      - run: terraform plan -out=tfplan
      - run: terraform apply -input=false tfplan
