name: Deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac/terraform
    env:
      TF_VAR_data_lake_bucket: ${{ secrets.DATA_LAKE_BUCKET }}
      TF_VAR_msk_cluster_name: ${{ secrets.MSK_CLUSTER_NAME }}
      TF_VAR_emr_application_name: ${{ secrets.EMR_APPLICATION_NAME }}
      TF_VAR_mwaa_env_name: ${{ secrets.MWAA_ENV_NAME }}
      TF_VAR_mwaa_dag_s3_path: ${{ secrets.MWAA_DAG_S3_PATH }}
      TF_VAR_mwaa_execution_role_arn: ${{ secrets.MWAA_EXECUTION_ROLE_ARN }}
      TF_VAR_mwaa_source_bucket_arn: ${{ secrets.MWAA_SOURCE_BUCKET_ARN }}

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - run: terraform plan -input=false -out=tfplan
      - run: terraform apply -input=false tfplan
        working-directory: iac/terraform
      - name: dbt docs
        run: |
          cd dbt && dbt docs generate
